@Library('library')_

pipeline
{
    agent any
    stages
    {
        stage('contdown_master')
        {
            steps
            {
                script
                {
                    cicd.gitdownload("maven1")
                }
            }
        }
         stage('contbuild_master')
        {
            steps
            {
                script
                {
                    cicd.build()
                }
            }
        }
        stage('contDeploy_master')
        {
            steps
            {
                script
                {
                    cicd. deploytomcat("DeclarativepipelineswithSharedLibraries","172.31.93.75","testapp")
                }
            }
        }
        stage('conttesting_master')
        {
            steps
            {
                script
                {
                    cicd.gitdownload("Functionaltesting")
                    cicd.runSelenium("DeclarativepipelineswithSharedLibraries")
                }
            }
        }
        stage('contDelivery_master')
        {
            steps
            {
                script
                {
                    cicd. deploytomcat("DeclarativepipelineswithSharedLibraries","172.31.84.240","prodapp")
                }
            }
        }
    }
}
